#!/bin/bash
# Generate gwiki-externaldocs.sty with \externaldocument for all notes

NOTES_DIR="notes"
OUTPUT="lib/gwiki-externaldocs.sty"

echo "% Auto-generated file - do not edit manually" > "$OUTPUT"
echo "% Generated by scripts/generate-externaldocs.sh" >> "$OUTPUT"
echo "" >> "$OUTPUT"

for file in $NOTES_DIR/*.tex; do
    if [ -f "$file" ]; then
        basename=$(basename "$file" .tex)
        # Use zexternaldocument for zref-xr package
        echo "\\IfFileExists{../build/pdf/$basename.aux}{\\zexternaldocument{../build/pdf/$basename}}{}" >> "$OUTPUT"
    fi
done

echo "" >> "$OUTPUT"
echo "\\endinput" >> "$OUTPUT"
